import Foundation

public struct ClipboardItem: Equatable, Identifiable {
    public let id: UUID
    public let text: String
    public let date: Date
    public init(id: UUID = UUID(), text: String, date: Date) { self.id = id; self.text = text; self.date = date }

    /// One-line preview for the tile.
    public var preview: String {
        text.split(whereSeparator: \.isNewline).map { $0.trimmingCharacters(in: .whitespaces) }.first(where: { !$0.isEmpty }) ?? text
    }
}

/// Recent text copies, newest first. Memory only: never written to disk.
public struct ClipboardHistory: Equatable {
    /// Pasteboard types that password managers and other apps use to mark a copy as secret or machine-made.
    public static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType",
    ]
    public static let maxLength = 5_000

    public private(set) var items: [ClipboardItem] = []
    public let capacity: Int

    public init(capacity: Int = 12) { self.capacity = max(1, capacity) }

    /// Returns true when the copy was kept.
    @discardableResult
    public mutating func add(_ text: String, types: [String], now: Date) -> Bool {
        guard !types.contains(where: Self.skippedTypes.contains) else { return false }
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty, text.count <= Self.maxLength else { return false }
        items.removeAll { $0.text == text }
        items.insert(ClipboardItem(text: text, date: now), at: 0)
        if items.count > capacity { items.removeLast(items.count - capacity) }
        return true
    }

    public mutating func remove(id: UUID) { items.removeAll { $0.id == id } }
    public mutating func clear() { items = [] }
}
